const p1 = Promise.resolve(0)
 p1.then(function (value) {
     console.log(value)
 })

 console.log("Some value")

//Catch the rejected promise....
 const p2 = Promise.rejected("Some Error")

 p2.catch( err => {
     console.log("error")
 })